### ISSUE TITLE
Consider replacing the `failure` crate by the `anyhow` crate.

### ISSUE THREAD

**Issue by alekseysidorov** [witnet/protobuf-convert#8]
It's no secret that `failure` actually deprecated because it have a fundamental flaws in the desigin.

In Exonum we replace `failure` by the `anyhow` crate, but now we need to write tricky code like this to use `anyhow` with the `protobuf-convert` derive.

https://github.com/exonum/exonum/blob/master/services/supervisor/src/proto_structures.rs#L15

In my opinion there are no any arguments against switching to `anyhow`.

If you agree I will make the corresponding PR to switch codegen to the `anyhow`.

**Comment by tmpolaczyk** [comment]
Ok, no problem.

If you know some blog post against using failure I would love to see if it's worth to deprecate it, as in Witnet we are using failure everywhere.

**Comment by aleksuss** [comment]
@tmpolaczyk Some information about that you can [here](https://github.com/dtolnay/anyhow#comparison-to-failure).

**Comment by alekseysidorov** [comment]
In my opinion the major `failure` drawback is an additional `Fail` trait. Modern error libraries uses only `std::error::Error` trait under the hood.
And in comparison to `snafu` `anyhow` is simplier and its API more like an old `failure`.

**Comment by mule-arrested** [comment]
to feel anyhow чувствовать себя расстроенным, больным
